[MAIN]
INPUT_RMQ_QUEUE = object-storage.models.quality.cgm
ELK_QUALITY_INDEX = emfos-model-quality
ELK_STATISTICS_INDEX = emfos-model-statistics
BORDER_LIMIT = 250
LINE_LIMIT_TEMPERATURE = 25 C
IGM_RULE_SET = impedance,line_rating
CGM_RULE_SET = kruonis,rtec,outage,lt_pl_xborder
#either a BA or EU
CGM_TYPE = BA
LINE_RATING_TSO_LIST = LITGRID,AST,ELERING
CROSSBORDER_CHECK_TSO_LIST = Augstsprieguma tikls,Litgrid,Elering,PSE S.A.
BRELL_LINES = 10T-LT-RU-00001W,10T-LT-RU-00002U,10T-LT-RU-00003S,10T-LV-RU-00001A,10T-LV-RU-00001A,10T-BY-LT-000053,10T-BY-LT-00001B,10T-BY-LT-000029,10T-EE-RU-00001M,10T-EE-RU-00002K,10T-EE-RU-00003I,10T-BY-LT-000045