
name: Build and Publish Docker Image

on:
  push:
    branches:
      - mk-3-docker
  pull_request:
    branches:
      - mk-3-docker

jobs:
  build:
    runs-on: ubuntu-latest

    variables:


    steps:
      - uses: actions/checkout@v4

      # Set multiple environment variables
      - name: Set Docker image tag and other variables
        id: vars
        run: |
          echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ vars.DOCKER_USERNAME }}/emfos-model-retriever" >> $GITHUB_ENV
          echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # Print env variables
      - name: Print environment variables
        run: env

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file docker/base/Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.TAG }}

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Image details
        run: echo "Image ${{ env.IMAGE_NAME }}:${{ env.TAG }} pushed to Docker Hub"
