
name: Build and Publish Docker Image

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file docker/base/Dockerfile --tag emfos-model-retriever:$(date +%s)

#      - name: Image details
#        run: echo "Image ${{ secrets.DOCKER_USERNAME }}/emfos-model-retriever:${{ github.sha }}"
