
name: Build and Publish Docker Image

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build the Docker image
      - name: Build the Docker image
#        run: docker build . --file docker/base/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/emfos-model-retriever:$(date +%s)
        run: docker build . --file docker/base/Dockerfile --tag emfos-model-retriever:$(date +%s)

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/emfos-model-retriever:$(date +%s)

      - name: Image details
        run: echo "Image ${{ secrets.DOCKER_USERNAME }}/emfos-model-retriever:$(date +%s) pushed to Docker Hub"
