
name: Build and Publish Docker Image

on:
  push:
    branches:
      - mk-3-docker
  pull_request:
    branches:
      - mk-3-docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Print env variables
      - name: Print environment variables
        run: env

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file docker/base/Dockerfile --tag ${{ variables.DOCKER_USERNAME }}/emfos-model-retriever:$(date +%s)
#        run: docker build . --file docker/base/Dockerfile --tag balticrcc/emfos-model-retriever:$(date +%s)

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ variables.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ variables.DOCKER_USERNAME }}/emfos-model-retriever:$(date +%s)

      - name: Image details
        run: echo "Image ${{ variables.DOCKER_USERNAME }}/emfos-model-retriever:$(date +%s) pushed to Docker Hub"
