name: Build and publish base image

on:
  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Base Image
        run: |
          docker build . \
            --file docker/Dockerfile \
            --target emfos-base \
            -t ${{ vars.DOCKER_USERNAME }}/emfos-base:latest
          docker push ${{ vars.DOCKER_USERNAME}}/emfos-base:latest


      - name: Display Success Message
        run: echo "emfos-base image has been built and pushed manually."
